# Generated by Django 4.2.16 on 2026-02-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.company'),
        ),
        migrations.AddField(
            model_name='battery',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battery.vehicle'),
        ),
    ]
