# Generated by Django 4.2.16 on 2026-03-03 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='subscriptio_user_id_b8c9e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='subscriptio_end_dat_7f8a9c_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this plan is currently available for subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False, help_text='Whether this plan includes priority customer support'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='swap_limit_per_month',
            field=models.IntegerField(help_text='Maximum number of battery swaps allowed per month'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
